const enData = {
	Global: {
		And: 'And',
	},
	Home: {
		Title: 'Home',
		Question: 'What is you like to eat?',
		SeeAll: 'See all',
		SearchStore: 'Search for Store',
	},
	Orders: {
		Title: 'ListOrders',
	},
	Cart: {
		Title: 'Cart',
	},
	Favorite: {
		Title: 'Favorite',
		tabFavorite: 'Favorite',
		tabMostOrder: 'Most Order',
	},
	Login: {
		Title: 'Welcome to store',
		Favorite: 'Your favorite meals delivered to you',
		Email: 'Email',
		Password: 'Password',
		Continue: 'Continue',
		LoginBy: 'Login by ',
		FingerId: 'FingerID',
		FaceId: 'FaceId',
		or: ' or ',
		Agree: 'By continuing you agree to our',
		TermOfServices: 'Terms of Service',
		Privacy: 'Privacy Policy',
		EmailRequire: 'Email is required',
		PasswordRequire: 'Password is required',
		LoginFailed: 'Wrong username or password',
	},
	ProductDetail: {
		detail: 'Product Detail',
		Nutritions: 'Nutritions',
		GenCode: 'GenCode: ',
		CodeArticle: 'Code article',
		Dlc: 'DLC',
		Submit: 'Ajouter au panier',
		Description: 'Description',
	},
	Intro: {
		WelcomeTo: 'Welcome to',
		OurStore: 'our store',
		Description: 'Ger your groceries in as fast as one hour',
		GetStart: 'Get started',
	},
	DropUp: {
		ChooseDate: 'Choose date delivery',
		ChooseDifferenceDate: 'Choose difference delivery date',
		Today: 'Today',
		Tomorrow: 'Tomorrow',
		Difference: 'Difference date',
		OrderDate: 'Choice order date',
		Note: 'Note',
		Submit: 'Submit order',
	},
};
export default enData;
