const enData = {
	Global: {
		And: 'And',
		PullToRefresh: 'Pull to refresh',
		EmptyList: 'There are currently no items.',
	},
	Home: {
		Title: 'Products',
		Question: 'What is you like to eat?',
		SeeAll: 'See all',
		SearchStore: 'Search for Store',
	},
	Orders: {
		Title: 'ListOrders',
		FilterMonth: 'Current month',
		ThreeMonth: '3 months ago',
		SixMonth: '6 months ago',
		CurrentYears: 'Current year',
		ClientCode: 'Code client',
		OrderCode: 'Order code',
		DeliveryDate: 'Delivery date',
		ProductAmount: '{value} Products',
		description: 'My orders',
		SeeOrder: 'To consult',
		Status: 'Status',
		ReOrder: 'Re-order',
		ProductList: 'Products List',
		CreateDate: 'Date of the order',
	},
	Cart: {
		Title: 'Cart',
		AddProductToCart: 'You have successfully added {value} product',
		AddProductToCartFail: 'You failed to add the product {value}',
		NoneProduct: 'There are no products in the cart.',
	},
	Favorite: {
		Title: 'Favorite',
		tabFavorite: 'My favorite',
		tabMostOrder: 'Most ordered',
	},
	Login: {
		Title: 'Welcome to the new !',
		Favorite: 'Your favorite meals delivered to you',
		Email: 'Your username',
		Password: 'Your password',
		Continue: 'Continue',
		LoginBy: 'Login by ',
		FingerId: 'FingerID',
		FaceId: 'FaceId',
		or: ' or ',
		Agree: 'By continuing you agree to our',
		TermOfServices: 'Terms of Service',
		Privacy: 'Privacy Policy',
		EmailRequire: 'Email is required',
		PasswordRequire: 'Password is required',
		LoginFailed: 'Wrong username or password',
	},
	ProductDetail: {
		detail: 'Product Detail',
		Nutritions: 'Nutritions',
		GenCode: 'GenCode: ',
		CodeArticle: 'Code article',
		Packacking: 'PACKACKING',
		Dlc: 'DLC',
		Submit: 'Submit',
		Description: 'Description',
	},
	Intro: {
		WelcomeTo: 'Welcome to',
		OurStore: 'our store',
		Description: 'Ger your groceries in as fast as one hour',
		GetStart: 'Get started',
	},
	ConfirmOrder: {
		description: 'Order request sent! \nYour order',
		note: 'Note on order',
	},
	Notifications: {
		Title: 'Notifications',
		StatusOrder: 'Order Status',
		MessageTab: 'Other messages',
	},
	Auth: {
		Logout: 'Sign out',
		LogoutContentPopup: 'Do you want to log out of your account?',
	},
	DropUp: {
		ChooseDate: 'Please choose the delivery date',
		ChooseDifferenceDate: 'Or choose your own delivery date',
		Today: 'Today',
		Tomorrow: 'Next day',
		Difference: 'Is different',
		OrderDate: 'Choice order date',
		Note: 'Order note',
		Submit: 'Send order request',
		SubmitFailTitle: 'Send failed',
		SubmitFailMessage: 'Please try again or contact customer service',
	},
	Other: {
		NewOrder: 'Your order has been accepted!',
		InPreparation: 'Your order is being prepared!',
		Delayed: 'Your order is being delayed!',
		Process: 'Your order has been successfully delivered!',
		Date: 'Date',
	},
	Setting: {
		TurnNotification: 'Turn on notifications',
		Language: 'Language',
		English: 'English',
		France: 'France',
	},
};
export default enData;
