const frData = {
	Global: {
		And: 'And',
		PullToRefresh: 'Tirer pour rafraîchir',
	},
	Home: {
		Title: 'Produits',
		Question: 'What is you like to eat?',
		SeeAll: 'See all',
		SearchStore: 'Search for Store',
	},
	Orders: {
		Title: 'Commandes',
		FilterMonth: 'Mois actuel',
		ThreeMonth: 'il y a 3 mois',
		SixMonth: 'il y a 6 mois',
		CurrentYears: 'année actuelle',
		ClientCode: 'Code client',
		OrderCode: 'Code de commande',
		DeliveryDate: 'Date de livraison',
		ProductAmount: '{value} Products',
		description: 'Mes commandes',
		SeeOrder: 'Consulter',
	},
	Cart: {
		Title: 'Cart',
		AddProductToCart: 'Vous avez ajouté avec succès {value} produit',
	},
	Favorite: {
		Title: 'Favoris',
		tabFavorite: 'Mes favoris',
		tabMostOrder: 'Le plus commandé',
	},
	Login: {
		Title: 'Bienvenue à nouveau !',
		Favorite: 'Your favorite meals delivered to you',
		Email: "votre nom d'utilisateur",
		Password: 'votre mot de passe',
		Continue: 'Connexion',
		LoginBy: 'Connexion par ',
		FingerId: 'FingerID',
		FaceId: 'FaceId',
		or: ' or ',
		Agree: 'By continuing you agree to our',
		TermOfServices: 'Terms of Service',
		Privacy: 'Privacy Policy',
		EmailRequire: 'Email is required',
		PasswordRequire: 'Password is required',
		LoginFailed: "Nom d'utilisateur ou mot de passe erroné",
	},
	ProductDetail: {
		detail: 'Product Detail',
		Nutritions: 'Nutritions',
		GenCode: 'GenCode: ',
		CodeArticle: 'Code article',
		Packaging: 'Emballage',
		Dlc: 'DLC',
		Submit: 'Ajouter au panier',
		Description: 'Description',
	},
	Intro: {
		WelcomeTo: 'Welcome to',
		OurStore: 'our store',
		Description: 'Ger your groceries in as fast as one hour',
		GetStart: 'Get started',
	},
	ConfirmOrder: {
		description: 'Demande de commande envoyée ! \nVotre commande',
		note: "Note sur l'ordre",
	},
	Notifications: {
		Title: 'Notifications',
		StatusOrder: 'Statut commande',
		MessageTab: 'Autres messages',
	},
	Auth: {
		Logout: 'Se déconnecter',
		LogoutContentPopup: 'Voulez-vous vous déconnecter de votre compte ?',
	},
	DropUp: {
		ChooseDate: 'Veuillez choisir la date de livraison',
		ChooseDifferenceDate: 'ou choisissez votre propre date de livraison',
		Today: "Aujourd'hui",
		Tomorrow: 'Jour suivant',
		Difference: 'Est différent',
		OrderDate: 'Choice order date',
		Note: 'Note sur la commande',
		Submit: "envoyer la demande d'ordre",
		SubmitFailTitle: 'La commande a échoué',
		SubmitFailMessage: 'Veuillez réessayer ou contacter le service client',
	},
	Other: {
		NewOrder: 'Votre commande a été acceptée !',
		InPreparation: 'Votre commande est en préparation !',
		Delayed: 'Votre commande est retardée !',
		Process: 'Votre commande a été livrée avec succès !',
	},
	Setting: {
		TurnNotification: 'Activer les notifications',
	},
};
export default frData;
